### ISSUE TITLE
Feature Request - Limit PR from other repos

### ISSUE THREAD

**Issue by dpaulson45** [LukBukkit/action-pr-limits#20]
Recently had an issue where someone opened up a PR to our releases branch directly instead of to our main branch.

We tried to implement this action, however, if our repository is forked and they commit a change on main and try to merge their main to releases, this check will still complete as successful.

Would like to see it be an option to only allow from the local repository and not a forked repository.

**Comment by lukbukkit** [comment]
Thanks for creating this issue. It's a good idea to introduce a input to only allow local pull requests for specific branches. I'm currently a bit time constrained but when I've got a bit of spare time, I can try to figure how to implement the feature.

**Comment by bill-long** [comment]
For now, we solved this by changing it to use `label` instead of `ref`:

https://github.com/LukBukkit/action-pr-limits/compare/main...bill-long:action-pr-limits:bilong-limit-by-repo-name

Our yml now looks like this:

```
name: Limit Pull Requests

on:
  pull_request:
    branches:
      - release

jobs:
  limit_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: bill-long/action-pr-limits@v1.0
        with:
          allowlist: |
            microsoft:main
```

Output from the action:

```
Pull request #1398: dpaulson45:main -> microsoft:release
Allowed Branches: ["microsoft:main"]
Forbidden Branches: []
Error: The pull request is forbidden. Branch 'dpaulson45:main' hasn't been found on the allowlist for 'microsoft:release'.
```

A fix that doesn't break everyone already using the action will be more complicated, but this seems to be doing the job as a quick fix for our use case.
